let STYLE_TEMPLATE_BYTES=null;
function styleSectionName(id){return({introA:"Intro A",mainA:"Main A",mainB:"Main B",fillA:"Fill In AA",endingA:"Ending A"}[id]||id)}
function textFromBytes(a){return String.fromCharCode(...a)}
function readU32(a,i){return (a[i]<<24)|(a[i+1]<<16)|(a[i+2]<<8)|a[i+3]}
function readVar(a,i){let v=0,b;do{b=a[i++];v=(v<<7)|(b&127)}while(b&128);return{v,i}}
function chanLen(s){let h=s&240;return(h===192||h===208)?1:2}
function parseTrack(a,start,end){let i=start,tick=0,run=0,out=[];while(i<end){let r=readVar(a,i);tick+=r.v;i=r.i;let status=a[i++],raw=[status];if(status<128){i--;status=run;raw=[]}else if(status<240){run=status}if(status===255){let type=a[i++],l=readVar(a,i);i=l.i;let data=[...a.slice(i,i+l.v)];i+=l.v;out.push({tick,kind:"meta",type,data,bytes:[255,type,...varLen(data.length),...data]});if(type===47)break}else if(status===240||status===247){let l=readVar(a,i);i=l.i;let data=[...a.slice(i,i+l.v)];i+=l.v;out.push({tick,kind:"sys",bytes:[status,...varLen(data.length),...data]})}else{let n=chanLen(status),data=[...a.slice(i,i+n)];i+=n;out.push({tick,kind:"midi",status,bytes:[status,...data]})}}return out}
function findTemplateParts(bytes){let a=[...bytes];if(textFromBytes(a.slice(0,4))!=="MThd")throw new Error("Template is not MIDI/STY");let ppq=(a[12]<<8)|a[13],m=a.findIndex((_,i)=>textFromBytes(a.slice(i,i+4))==="MTrk");if(m<0)throw new Error("Template has no MTrk");let len=readU32(a,m+4),start=m+8,end=start+len;return{a,ppq,head:a.slice(0,start),trackStart:start,trackEnd:end,tail:a.slice(end),events:parseTrack(a,start,end)}}
function sectionTicks(events){let map={};for(const e of events){if(e.kind==="meta"&&e.type===6){let t=textFromBytes(e.data);for(const id of ["introA","mainA","mainB","fillA","endingA"]){if(t===styleSectionName(id)&&map[id]==null)map[id]=e.tick}}}let fallback=0;for(const id of ["introA","mainA","mainB","fillA","endingA"]){if(map[id]==null){map[id]=fallback;fallback+=768}}return map}
function projectMidiEvents(ppq,marks){let ev=[];for(const id of ["introA","mainA","mainB","fillA","endingA"]){let sec=project.sections[id];if(!sec)continue;let base=marks[id]||0;let tracks=(typeof activeTracks==="function")?activeTracks(sec):sec.tracks;for(const tr of tracks){for(const n of tr.notes){let ch=tr.midiChannel||9,t=base+Math.round(n.start*ppq),d=Math.round((n.duration||0.25)*ppq);ev.push({tick:t,bytes:[192+ch,0]});ev.push({tick:t,bytes:[144+ch,n.pitch,n.velocity||100]});ev.push({tick:t+d,bytes:[128+ch,n.pitch,0]})}}}return ev}
function rebuildTrack(events){events.sort((a,b)=>a.tick-b.tick);let bytes=[],last=0;for(const e of events){bytes.push(...varLen(Math.max(0,e.tick-last)),...e.bytes);last=e.tick}return bytes}
function u32bytes(n){return[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255]}
function injectIntoTemplate(){if(!STYLE_TEMPLATE_BYTES)throw new Error("Load a working STY template first");project.name=styleName.value||"Untitled Style";let p=findTemplateParts(STYLE_TEMPLATE_BYTES),marks=sectionTicks(p.events);let keep=p.events.filter(e=>e.kind!=="midi"&&!(e.kind==="meta"&&e.type===47)).map(e=>({tick:e.tick,bytes:e.bytes}));let endTick=Math.max(...p.events.map(e=>e.tick),0);let all=[...keep,...projectMidiEvents(p.ppq,marks),{tick:endTick,bytes:[255,47,0]}];let trk=rebuildTrack(all);return new Uint8Array([...p.a.slice(0,p.trackStart-4),...u32bytes(trk.length),...trk,...p.tail])}
function buildExperimentalStyleBytes(){if(STYLE_TEMPLATE_BYTES)return injectIntoTemplate();alert("Load a working STY template first. For now use PIANOBAL.STY as the skeleton.");return null}
function exportExperimentalStyle(){let sty=buildExperimentalStyleBytes();if(!sty)return;downloadBlob(sty,`${safeName(project.name)}-template-injected.sty`,"application/octet-stream")}
window.addEventListener("DOMContentLoaded",()=>{let btn=document.getElementById("exportStyleBtn");if(btn)btn.onclick=exportExperimentalStyle;let input=document.getElementById("templateStyleInput");if(input)input.onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{STYLE_TEMPLATE_BYTES=new Uint8Array(r.result);alert("STY template loaded: "+f.name)};r.readAsArrayBuffer(f)}});