let STYLE_TEMPLATE_BYTES=null,LAST_EXPORT_DEBUG="";
function styleSectionName(id){return({introA:"Intro A",mainA:"Main A",mainB:"Main B",fillA:"Fill In AA",fillAB:"Fill In AB",fillBA:"Fill In BA",fillBB:"Fill In BB",endingA:"Ending A"}[id]||id)}
function bytesText(a){let s="";for(let i=0;i<a.length;i++)s+=String.fromCharCode(a[i]);return s}
function readU32(a,i){return ((a[i]<<24)>>>0)+(a[i+1]<<16)+(a[i+2]<<8)+a[i+3]}
function readVar(a,i){let v=0,b=0;do{b=a[i++];v=(v<<7)+(b&127)}while((b&128)&&i<a.length);return{v,i}}
function putStatus(msg){let el=document.getElementById("templateStatus");if(el)el.textContent=msg;else console.log(msg)}
function chanDataLen(s){let h=s&240;return(h===192||h===208)?1:2}
function findMTrk(a){for(let i=0;i<a.length-4;i++){if(a[i]===77&&a[i+1]===84&&a[i+2]===114&&a[i+3]===107)return i}return-1}
function parseTrack(a,start,end){let i=start,tick=0,run=0,out=[];while(i<end){let r=readVar(a,i);tick+=r.v;i=r.i;let status=a[i++];if(status<128){i--;status=run}else if(status<240){run=status}if(status===255){let type=a[i++],l=readVar(a,i);i=l.i;let data=Array.from(a.slice(i,i+l.v));i+=l.v;out.push({tick,kind:"meta",type,data,bytes:[255,type,...varLen(data.length),...data]});if(type===47)break}else if(status===240||status===247){let l=readVar(a,i);i=l.i;let data=Array.from(a.slice(i,i+l.v));i+=l.v;out.push({tick,kind:"sys",bytes:[status,...varLen(data.length),...data]})}else if(status>0){let n=chanDataLen(status),data=Array.from(a.slice(i,i+n));i+=n;out.push({tick,kind:"midi",status,bytes:[status,...data]})}else break}return out}
function findTemplateParts(bytes){let a=Array.from(bytes);if(bytesText(a.slice(0,4))!=="MThd")throw new Error("Template is not MIDI/STY");let ppq=(a[12]<<8)+a[13],m=findMTrk(a);if(m<0)throw new Error("Template has no MTrk");let len=readU32(a,m+4),start=m+8,end=start+len;return{a,ppq,trackStart:start,tail:a.slice(end),events:parseTrack(a,start,end)}}
function markerTicks(events,label){let out=[];for(let e of events){if(e.kind==="meta"&&e.type===6&&bytesText(e.data)===label)out.push(e.tick)}return out}
function markerMap(events){let labels=["SInt","Intro A","Main A","Main B","Fill In AA","Fill In AB","Fill In BA","Fill In BB","Ending A"],arr=[];for(let e of events){if(e.kind==="meta"&&e.type===6){let t=bytesText(e.data);if(labels.includes(t))arr.push({label:t,tick:e.tick})}}arr.sort((a,b)=>a.tick-b.tick);let last=events.reduce((m,e)=>Math.max(m,e.tick),0),map={};for(let i=0;i<arr.length;i++){let next=i<arr.length-1?arr[i+1].tick:last;map[arr[i].label]={start:arr[i].tick,end:next,span:Math.max(1,next-arr[i].tick)}}return map}
function sectionInfo(events){let m=markerMap(events),fallback=768;return{introA:m["Intro A"]||{start:0,end:fallback,span:fallback},mainA:m["Main A"]||{start:fallback,end:fallback*2,span:fallback},mainB:m["Main B"]||{start:fallback*2,end:fallback*3,span:fallback},fillA:m["Fill In AA"]||m["Fill In AB"]||{start:fallback*3,end:fallback*4,span:fallback},fillAB:m["Fill In AB"]||m["Fill In AA"]||{start:fallback*3,end:fallback*4,span:fallback},fillBA:m["Fill In BA"]||m["Fill In BB"]||{start:fallback*4,end:fallback*5,span:fallback},fillBB:m["Fill In BB"]||m["Fill In BA"]||{start:fallback*4,end:fallback*5,span:fallback},endingA:m["Ending A"]||{start:fallback*5,end:fallback*6,span:fallback}}}
function tempoMeta(){return[255,81,3,...tempoBytes(Number(project.tempo)||120)]}
function normalizedKeepEvent(e){if(e.kind==="meta"&&e.type===81)return{tick:e.tick,bytes:tempoMeta()};return{tick:e.tick,bytes:e.bytes}}
function exportPlan(){if(project.keyboard==="PSR-E Series")return[{src:"introA",slot:"introA"},{src:"mainA",slot:"mainA"},{src:"mainB",slot:"mainB"},{src:"fillA",slot:"fillA"},{src:"fillA",slot:"fillAB"},{src:"fillBA",slot:"fillBA"},{src:"fillBA",slot:"fillBB"},{src:"endingA",slot:"endingA"}];return[{src:"introA",slot:"introA"},{src:"mainA",slot:"mainA"},{src:"mainB",slot:"mainB"},{src:"fillA",slot:"fillA"},{src:"endingA",slot:"endingA"}]}
function trackLabel(tr){return({rhythm1:"Drums",bass:"Bass",chord1:"Chords1",chord2:"Chords2",pad:"Pad",phrase1:"Phrases",phrase2:"Phrase2",rhythm2:"Rhythm2"}[tr.id]||tr.id)}
function projectMidiEvents(ppq,info){let ev=[],dbg=[],projectSpan=ppq*4*BAR_COUNT;if(projectSpan<1)projectSpan=ppq*4;for(let item of exportPlan()){let sec=project.sections[item.src];if(!sec)continue;let si=info[item.slot];if(!si)continue;let tracks=(typeof activeTracks==="function")?activeTracks(sec):sec.tracks,repeats=Math.max(1,Math.ceil(si.span/projectSpan)),counts={};for(let r=0;r<repeats;r++){let off=si.start+r*projectSpan;for(let tr of tracks){counts[trackLabel(tr)]=(counts[trackLabel(tr)]||0)+tr.notes.length;for(let n of tr.notes){let local=Math.round(n.start*ppq);if(local>=projectSpan)continue;let ch=tr.midiChannel||9,t=off+local,d=Math.round((n.duration||0.25)*ppq);if(t>=si.end)continue;if(t+d>si.end)d=Math.max(1,si.end-t);ev.push({tick:t,bytes:[192+ch,0]});ev.push({tick:t,bytes:[144+ch,n.pitch,n.velocity||100]});ev.push({tick:t+d,bytes:[128+ch,n.pitch,0]})}}}dbg.push(item.slot+"←"+item.src+" "+Object.entries(counts).map(([k,v])=>k+":"+v).join(","))}LAST_EXPORT_DEBUG="Export: "+dbg.join(" | ");return ev}
function rebuildTrack(events){events.sort((a,b)=>a.tick-b.tick);let bytes=[],last=0;for(let e of events){bytes.push(...varLen(Math.max(0,e.tick-last)));for(let b of e.bytes)bytes.push(b);last=e.tick}return bytes}
function u32bytes(n){return[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255]}
function templateSummary(bytes,name){try{let p=findTemplateParts(bytes),info=sectionInfo(p.events),bits=[];for(let id of ["introA","mainA","mainB","fillA","fillAB","fillBA","fillBB","endingA"]){let s=info[id];if(s){let bars=Math.max(1,Math.round(s.span/(p.ppq*4)));bits.push(styleSectionName(id)+":"+bars)}}putStatus("Template: "+name+" • "+bits.join(" • "))}catch(e){putStatus("Template loaded, but summary failed: "+e.message)}}
function injectIntoTemplate(){if(!STYLE_TEMPLATE_BYTES)throw new Error("Load a working STY template first");project.name=styleName.value||"Untitled Style";project.tempo=Number(tempo.value)||120;let p=findTemplateParts(STYLE_TEMPLATE_BYTES),info=sectionInfo(p.events);let keep=p.events.filter(e=>e.kind!=="midi"&&!(e.kind==="meta"&&e.type===47)).map(normalizedKeepEvent);let endTick=p.events.reduce((m,e)=>Math.max(m,e.tick),0);let all=keep.concat(projectMidiEvents(p.ppq,info)).concat([{tick:endTick,bytes:[255,47,0]}]);let trk=rebuildTrack(all);return new Uint8Array(p.a.slice(0,p.trackStart-4).concat(u32bytes(trk.length),trk,p.tail))}
function buildExperimentalStyleBytes(){if(STYLE_TEMPLATE_BYTES)return injectIntoTemplate();alert("Load a working STY template first. For now use PIANOBAL.STY as the skeleton.");return null}
function exportExperimentalStyle(){try{let sty=buildExperimentalStyleBytes();if(!sty)return;downloadBlob(sty,`${safeName(project.name)}-template-injected.sty`,"application/octet-stream");putStatus(LAST_EXPORT_DEBUG)}catch(e){alert("STY export failed: "+e.message);putStatus("STY export failed: "+e.message)}}
window.addEventListener("DOMContentLoaded",()=>{putStatus("STY exporter ready. Load a template.");let btn=document.getElementById("exportStyleBtn");if(btn)btn.onclick=exportExperimentalStyle;let input=document.getElementById("templateStyleInput");if(input)input.onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{STYLE_TEMPLATE_BYTES=new Uint8Array(r.result);templateSummary(STYLE_TEMPLATE_BYTES,f.name);alert("STY template loaded: "+f.name)};r.onerror=()=>putStatus("Template load failed");r.readAsArrayBuffer(f)}});