const TIMELINE_TRACKS=[
  {id:"rhythm1",name:"Rhythm 1",midiChannel:9},{id:"rhythm2",name:"Rhythm 2",midiChannel:8},{id:"bass",name:"Bass",midiChannel:10},{id:"chord1",name:"Chord 1",midiChannel:11},{id:"chord2",name:"Chord 2",midiChannel:12},{id:"pad",name:"Pad",midiChannel:13},{id:"phrase1",name:"Phrase 1",midiChannel:14},{id:"phrase2",name:"Phrase 2",midiChannel:15}
];
const TIMELINE_PROFILES={
  "PSR-E Series":{mode:"builtin-psre",tracks:[["rhythm1","Drums"],["bass","Bass"],["chord1","Chords 1"],["chord2","Chords 2"],["pad","Pad"],["phrase1","Phrases"]],sections:[["mainA","Main A","Main A"],["mainB","Main B","Main B"],["fillA","Fill A→B","Fill In AA + AB"],["fillBA","Fill B→A","Fill In BA + BB"],["introA","Intro A","Intro A"],["endingA","Ending A","Ending A"]]},
  "PSR-SX600":{mode:"builtin-sx",tracks:[["rhythm1","Rhythm 1"],["rhythm2","Rhythm 2"],["bass","Bass"],["chord1","Chord 1"],["chord2","Chord 2"],["pad","Pad"],["phrase1","Phrase 1"],["phrase2","Phrase 2"]],sections:[["mainA","Main A","Main A"],["mainB","Main B","Main B"],["mainC","Main C","Main C"],["mainD","Main D","Main D"],["fillA","Fill A","Fill In AA"],["fillB","Fill B","Fill In BB + BA"],["fillC","Fill C","Fill In CC"],["fillD","Fill D","Fill In DD"],["introA","Intro A","Intro A"],["introB","Intro B","Intro B"],["introC","Intro C","Intro C"],["endingA","Ending A","Ending A"],["endingB","Ending B","Ending B"],["endingC","Ending C","Ending C"]]}
};
const TIMELINE_SECTION_IDS=["mainA","mainB","mainC","mainD","fillA","fillB","fillC","fillD","fillBA","introA","introB","introC","endingA","endingB","endingC"];
let BAR_COUNT=1;
let project=createTimelineProject();
var styleName=document.getElementById("styleName");
var tempo=document.getElementById("tempo");
const keyboardSelect=document.getElementById("keyboardSelect"),sectionSelect=document.getElementById("sectionSelect"),barsSelect=document.getElementById("barsSelect"),targetTrackSelect=document.getElementById("targetTrackSelect"),sourceChannelSelect=document.getElementById("sourceChannelSelect"),replaceTargetCheck=document.getElementById("replaceTargetCheck"),midiImportInput=document.getElementById("midiImportInput"),loadTimelineInput=document.getElementById("loadTimelineInput"),importStatus=document.getElementById("importStatus"),sectionMap=document.getElementById("sectionMap"),timeline=document.getElementById("timeline"),timelineTitle=document.getElementById("timelineTitle"),timelineHelp=document.getElementById("timelineHelp"),timelineSpan=document.getElementById("timelineSpan"),styExportMode=document.getElementById("styExportMode");

function defaultVoice(id){if(id==="rhythm1"||id==="rhythm2")return"Standard Kit";if(id==="bass")return"Finger Bass";if(id==="pad")return"Warm Pad";return"Grand Piano"}
function makeTimelineSection(){return{bars:BAR_COUNT,stepsPerBar:16,tracks:TIMELINE_TRACKS.map(track=>({...track,voice:defaultVoice(track.id),notes:[]}))}}
function createTimelineProject(){let sections={};TIMELINE_SECTION_IDS.forEach(id=>sections[id]=makeTimelineSection());return{app:"StyleForge MIDI Timeline",version:"1.3.0",name:"Timeline Style",tempo:120,barCount:1,timeSignature:"4/4",keyboard:"PSR-E Series",sections}}
function currentProfile(){return TIMELINE_PROFILES[project.keyboard]||TIMELINE_PROFILES["PSR-E Series"]}
function activeTrackIds(){return currentProfile().tracks.map(item=>item[0])}
function activeTracks(section){return(section||project.sections[currentSection()]).tracks.filter(track=>activeTrackIds().includes(track.id))}
function currentSection(){return sectionSelect.value||currentProfile().sections[0][0]}
function trackDisplay(id){let item=currentProfile().tracks.find(track=>track[0]===id);return item?item[1]:id}
function sectionDetails(id=currentSection()){return currentProfile().sections.find(section=>section[0]===id)||currentProfile().sections[0]}
function currentTrack(){return project.sections[currentSection()].tracks.find(track=>track.id===targetTrackSelect.value)||activeTracks()[0]}
function tempoBytes(bpm){let mpqn=Math.round(60000000/bpm);return[(mpqn>>16)&255,(mpqn>>8)&255,mpqn&255]}
function safeName(name){return String(name).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"styleforge"}
function downloadBlob(content,filename,type){let blob=new Blob([content],{type}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=filename;link.click();URL.revokeObjectURL(link.href)}
function formatChannel(channel){return`MIDI channel ${channel+1}`}
function noteLabel(pitch){let names=["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"];return names[pitch%12]+(Math.floor(pitch/12)-1)}
function migrateTimelineProject(){BAR_COUNT=Number(project.barCount||1);if(![1,2,4].includes(BAR_COUNT))BAR_COUNT=1;project.barCount=BAR_COUNT;project.keyboard=TIMELINE_PROFILES[project.keyboard]?project.keyboard:"PSR-E Series";project.sections=project.sections||{};TIMELINE_SECTION_IDS.forEach(id=>{if(!project.sections[id])project.sections[id]=makeTimelineSection()});Object.values(project.sections).forEach(section=>{section.bars=BAR_COUNT;section.stepsPerBar=16;section.tracks=section.tracks||[];TIMELINE_TRACKS.forEach(base=>{if(!section.tracks.some(track=>track.id===base.id))section.tracks.push({...base,voice:defaultVoice(base.id),notes:[]})});section.tracks.forEach(track=>{track.notes=(track.notes||[]).filter(note=>Number.isFinite(note.pitch)&&Number.isFinite(note.start)&&note.start<BAR_COUNT*4)})})}
function renderControls(){migrateTimelineProject();styleName.value=project.name;tempo.value=project.tempo;barsSelect.value=String(BAR_COUNT);keyboardSelect.value=project.keyboard;let previousSection=currentSection(),previousSource=sourceChannelSelect.value;sectionSelect.innerHTML=currentProfile().sections.map(([id,label])=>`<option value="${id}">${label}</option>`).join("");sectionSelect.value=currentProfile().sections.some(section=>section[0]===previousSection)?previousSection:currentProfile().sections[0][0];let previousTrack=targetTrackSelect.value;targetTrackSelect.innerHTML=activeTracks().map(track=>`<option value="${track.id}">${trackDisplay(track.id)} — ${formatChannel(track.midiChannel)}</option>`).join("");targetTrackSelect.value=activeTracks().some(track=>track.id===previousTrack)?previousTrack:activeTracks()[0].id;sourceChannelSelect.innerHTML=Array.from({length:16},(_,index)=>`<option value="${index}">MIDI channel ${index+1}</option>`).join("");sourceChannelSelect.value=sourceChannelSelect.dataset.userSelected?previousSource:String(currentTrack().midiChannel);let details=sectionDetails();sectionMap.textContent=`${details[1]} exports to Yamaha slot${details[2].includes(" + ")?"s":""}: ${details[2]}.`;timelineTitle.textContent=`${details[1]} Timeline`;timelineHelp.textContent=`Import a source channel into ${trackDisplay(currentTrack().id)} (${formatChannel(currentTrack().midiChannel)} on the generated style).`;timelineSpan.textContent=`${BAR_COUNT} ${BAR_COUNT===1?"bar":"bars"} / ${BAR_COUNT*16} steps`;styExportMode.value=currentProfile().mode;if(typeof syncStyleExportProfile==="function")syncStyleExportProfile();renderTimeline()}
function renderTimeline(){let tracks=activeTracks(),steps=BAR_COUNT*16,totalQuarters=BAR_COUNT*4;ruler=`<div class="timeline-ruler" style="--timeline-steps:${steps}"><div class="timeline-corner">Track / output channel</div>${Array.from({length:steps},(_,index)=>`<div class="timeline-step-label">${index%4===0?`| ${Math.floor(index/4)+1}`:index+1}</div>`).join("")}</div>`;let rows=tracks.map(track=>{let notes=track.notes||[],active=track.id===currentTrack().id?" active":"",blocks=notes.map(note=>{let left=Math.max(0,Math.min(100,note.start/totalQuarters*100)),width=Math.max(.7,Math.min(100-left,(note.duration||.25)/totalQuarters*100)),drum=track.id.startsWith("rhythm")?" drum":"";return`<div class="timeline-note${drum}" style="left:${left}%;width:${width}%" title="${noteLabel(note.pitch)} · start ${note.start} · duration ${note.duration||.25}">${noteLabel(note.pitch)}</div>`}).join("");return`<div class="timeline-row" style="--timeline-steps:${steps}"><button class="timeline-track${active}" data-track="${track.id}"><strong>${trackDisplay(track.id)}</strong><span>${formatChannel(track.midiChannel)} · ${notes.length} notes</span></button>${notes.length?`<div class="timeline-lane">${blocks}</div>`:`<div class="timeline-empty">No imported notes</div>`}</div>`}).join("");timeline.innerHTML=ruler+rows;timeline.querySelectorAll("[data-track]").forEach(button=>button.onclick=()=>{targetTrackSelect.value=button.dataset.track;sourceChannelSelect.value=String(currentTrack().midiChannel);sourceChannelSelect.dataset.userSelected="";renderControls()})}
function readU32(bytes,index){return((bytes[index]<<24)>>>0)+(bytes[index+1]<<16)+(bytes[index+2]<<8)+bytes[index+3]}
function readVlq(bytes,index){let value=0,byte=0;do{if(index>=bytes.length)throw new Error("Unexpected end of MIDI data");byte=bytes[index++];value=(value<<7)|(byte&127)}while(byte&128);return{value,index}}
function channelDataLength(status){let type=status&240;return type===192||type===208?1:2}
function parseMidi(bytes){if(String.fromCharCode(...bytes.slice(0,4))!=="MThd")throw new Error("The selected file is not a Standard MIDI file.");let headerLength=readU32(bytes,4),format=(bytes[8]<<8)|bytes[9],trackCount=(bytes[10]<<8)|bytes[11],ppq=(bytes[12]<<8)|bytes[13];if(!ppq||ppq&0x8000)throw new Error("SMPTE-timed MIDI files are not supported.");let position=8+headerLength,events=[],order=0,tempoValue=null;for(let track=0;track<trackCount;track++){if(String.fromCharCode(...bytes.slice(position,position+4))!=="MTrk")throw new Error("MIDI track chunk is missing or corrupt.");let end=position+8+readU32(bytes,position+4),cursor=position+8,tick=0,running=0;while(cursor<end){let delta=readVlq(bytes,cursor);tick+=delta.value;cursor=delta.index;let status=bytes[cursor++];if(status<128){if(!running)throw new Error("Invalid running status in MIDI data.");cursor--;status=running}else if(status<240)running=status;if(status===255){let type=bytes[cursor++],length=readVlq(bytes,cursor);cursor=length.index;if(type===81&&length.value===3&&tempoValue===null)tempoValue=(bytes[cursor]<<16)|(bytes[cursor+1]<<8)|bytes[cursor+2];cursor+=length.value;continue}if(status===240||status===247){let length=readVlq(bytes,cursor);cursor=length.index+length.value;continue}if(status<128||status>239)throw new Error("Unsupported MIDI event in source file.");let dataLength=channelDataLength(status),data1=bytes[cursor++],data2=dataLength===2?bytes[cursor++]:0,type=status&240,channel=status&15;if(type===144&&data2>0)events.push({tick,channel,pitch:data1,velocity:data2,on:true,order:order++});else if(type===128||(type===144&&data2===0))events.push({tick,channel,pitch:data1,velocity:0,on:false,order:order++})}position=end}events.sort((a,b)=>a.tick-b.tick||(a.on===b.on? a.order-b.order:a.on?1:-1));let open=new Map(),notes=[];events.forEach(event=>{let key=`${event.channel}:${event.pitch}`,stack=open.get(key)||[];if(event.on){stack.push(event);open.set(key,stack)}else if(stack.length){let start=stack.shift();if(!stack.length)open.delete(key);if(event.tick>start.tick)notes.push({channel:event.channel,pitch:event.pitch,velocity:start.velocity,start:start.tick/ppq,duration:(event.tick-start.tick)/ppq})}});return{format,ppq,tempo:tempoValue?Math.round(60000000/tempoValue):null,notes}}
function importMidi(file){let reader=new FileReader();reader.onload=()=>{try{let parsed=parseMidi(new Uint8Array(reader.result)),track=currentTrack(),sourceChannel=Number(sourceChannelSelect.value),incoming=parsed.notes.filter(note=>note.channel===sourceChannel&&note.start<BAR_COUNT*4).map(note=>({pitch:note.pitch,start:Math.round(note.start*96)/96,duration:Math.max(1/96,Math.round(note.duration*96)/96),velocity:note.velocity}));incoming.forEach(note=>{if(note.start+note.duration>BAR_COUNT*4)note.duration=Math.max(1/96,BAR_COUNT*4-note.start)});if(replaceTargetCheck.checked)track.notes=[];track.notes.push(...incoming);track.notes.sort((a,b)=>a.start-b.start||a.pitch-b.pitch);if(parsed.tempo){project.tempo=parsed.tempo;tempo.value=parsed.tempo}importStatus.textContent=`Imported ${incoming.length} notes from MIDI channel ${sourceChannel+1} into ${trackDisplay(track.id)} for ${sectionDetails()[1]}. Source: format ${parsed.format}, PPQ ${parsed.ppq}.`;renderControls()}catch(error){importStatus.textContent=`MIDI import failed: ${error.message}`}};reader.onerror=()=>importStatus.textContent="MIDI import failed while reading the file.";reader.readAsArrayBuffer(file)}
function clearTargetTrack(){let track=currentTrack();track.notes=[];importStatus.textContent=`Cleared ${trackDisplay(track.id)} in ${sectionDetails()[1]}.`;renderControls()}
function clearCurrentSection(){activeTracks().forEach(track=>track.notes=[]);importStatus.textContent=`Cleared all ${activeTracks().length} active tracks in ${sectionDetails()[1]}.`;renderControls()}
function saveTimeline(){project.name=styleName.value||"Timeline Style";project.tempo=Number(tempo.value)||120;downloadBlob(JSON.stringify(project,null,2),`${safeName(project.name)}.timeline.json`,"application/json")}
function loadTimeline(file){let reader=new FileReader();reader.onload=()=>{try{project=JSON.parse(reader.result);migrateTimelineProject();importStatus.textContent="Timeline project loaded.";renderControls()}catch{importStatus.textContent="Could not load the timeline JSON project."}};reader.readAsText(file)}
function setBars(value){BAR_COUNT=value;project.barCount=value;Object.values(project.sections).forEach(section=>section.tracks.forEach(track=>track.notes=track.notes.filter(note=>note.start<value*4)));renderControls()}
keyboardSelect.onchange=()=>{project.keyboard=keyboardSelect.value;sourceChannelSelect.dataset.userSelected="";renderControls()};sectionSelect.onchange=()=>renderControls();barsSelect.onchange=()=>setBars(Number(barsSelect.value));targetTrackSelect.onchange=()=>{sourceChannelSelect.value=String(currentTrack().midiChannel);sourceChannelSelect.dataset.userSelected="";renderControls()};sourceChannelSelect.onchange=()=>sourceChannelSelect.dataset.userSelected="true";styleName.oninput=()=>project.name=styleName.value;tempo.oninput=()=>project.tempo=Number(tempo.value)||120;midiImportInput.onchange=event=>{let file=event.target.files[0];if(file)importMidi(file);event.target.value=""};document.getElementById("clearTrackBtn").onclick=clearTargetTrack;document.getElementById("clearSectionBtn").onclick=clearCurrentSection;document.getElementById("saveTimelineBtn").onclick=saveTimeline;loadTimelineInput.onchange=event=>{let file=event.target.files[0];if(file)loadTimeline(file);event.target.value=""};renderControls();
